apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc_name }}
spec:
  storageClassName: {{ .Values.sc_name }}
  accessModes:
    - {{ .Values.access_modes }}
  resources:
    requests:
      storage: {{ .Values.capacity }}