apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service1_name }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service_port }}
      targetPort:  {{ .Values.deploy_port }}
  type: NodePort
