apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service2_name }}
spec:
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: {{ .Values.service_port }}
      targetPort:  {{ .Values.deploy_port }}
  type: NodePort
