deploy_name: nginx-deployment
deploy2_name: nginx-deployment2

deploy_port: 8080

deploy_replicas: 3

deploy1_image: 
  repository: gcr.io/google-samples/hello-app
  tag: "1.0"

deploy2_image: 
  repository: gcr.io/google-samples/hello-app
  tag: "2.0"

service_port: 80

service1_name: my-service
service2_name: my-service2

ingress_name: minimal-ingress
ingress_path1: /
ingress_path2: /hello